### ISSUE TITLE
Typo in Readme and help (-nogui argument)

### ISSUE THREAD

**Issue by kvnmtz** [kettingpowered/kettinglauncher#25]
In the readme's arguments table, the -nogui argument is labeled as "-noui", which did not work for me while "-nogui" did.
Also when running the launcher with -help "-noui" is shown.

**Comment by C0D3-M4513R** [comment]
`-nogui` and `-noui` are two seperate arguments.
The `-noui` argument is a kettinglauncher argument, that controls the Ketting logo.
`-nogui` is a Minecraft argument and thus not listed, since Minecraft arguments can vary across versions.

**Comment by kvnmtz** [comment]
Oh I see, sorry about this issue then :D
