### ISSUE TITLE
How to pass JVM args like -Xmx etc?

### ISSUE THREAD

**Issue by ivxvm** [kettingpowered/kettinglauncher#36]
All other servers I've seen use a special file like "user_jvm_args.txt", but here I'm not sure what to do, couldn't find any documentation on this either. I basically want to limit RAM usage for JVM with a flag like "-Xmx12G". This is what I tried and it didn't work:
```
java -jar .\kettinglauncher-1.3.8.jar -noui -accepteula -daus -daul -minecraftVersion 1.20.1 -forgeVersion 47.2.20 -Xmx12G
```

**Comment by C0D3-M4513R** [comment]
All usual java arguments go where they usually do:
`java -Xmx12G -jar .\kettinglauncher-1.3.8.jar -noui -accepteula -daus -daul -minecraftVersion 1.20.1 -forgeVersion 47.2.20`

Also most forge versions are compatible, except that sometimes mod devs put arbitrary limits.
Thus we do not recommend specifying `-forgeVersion`, as it can lead to your server being very out of date. (in this case you are 18 releases behind)

**Comment by ivxvm** [comment]
> All usual java arguments go where they usually do: `java -Xmx12G -jar .\kettinglauncher-1.3.8.jar -noui -accepteula -daus -daul -minecraftVersion 1.20.1 -forgeVersion 47.2.20`
> 
> Also most forge versions are compatible, except that sometimes mod devs put arbitrary limits. Thus we do not recommend specifying `-forgeVersion`, as it can lead to your server being very out of date. (in this case you are 18 releases behind)

Thanks, but is that guaranteed that passing -Xmx12G like that will make it go to server process itself and not only to kettinglauncher?

**Comment by C0D3-M4513R** [comment]
the kettinglauncher process is the server process.
