### ISSUE TITLE
Crashing on start up With ATM9

### ISSUE THREAD

**Issue by HowdyItsCurtis69** [kettingpowered/kettinglauncher#37]
I tried launching [kettinglauncher], specifically this version [kettinglauncher-1.3.8.jar], the newest version, with my All the Mods 9 server. It never starts; it runs for about 30 seconds and then crashes. Here are all the logs and crash reports I could find. I didn't know exactly what information you needed to help me or prevent this in the future, so I'm sending everything. 

[Test.txt](https://github.com/user-attachments/files/15845104/Test.txt)
[debug.log](https://github.com/user-attachments/files/15845105/debug.log)
[latest.log](https://github.com/user-attachments/files/15845106/latest.log)

Here is a link to the complete mod list. https://www.modpackindex.com/modpack/64056/all-the-mods-9-atm9

**Comment by p0t4t0sandwich** [comment]
Please re-create this issue over at: https://github.com/kettingpowered/Ketting-1-20-x/issues
Then close this issue.
