### ISSUE TITLE
Ice and Fire unknown entities

### ISSUE THREAD

**Issue by noodlebowls** [kettingpowered/kettinglauncher#39]
### Basic questions:

- [x] I am using the latest Ketting launcher version at the time of writing.
- [ ] I am not running my server in a onedrive folder.
- [ ] I have provided full logs and not a screenshot.
- [ ] I am having an issue with ketting and not the ketting launcher.
- [ ] I have checked all items without reading.
- [ ] I have provided proper reproduction steps.

### Ketting launcher Version

1.4.1

### Description of behavior

![image](https://github.com/user-attachments/assets/4fc9de9d-e177-476e-a4a0-febdd8d32c25)
also dragon corpses dont drop scales or bones/skull

### Reproduction Steps

```markdown
Steps to reproduce the behavior:
1. Use above Version with
2. Run the server
3. See the error
```

### Logs

https://mclo.gs/klWyXyC

### JVM Flags

unsure

### Operating system

Windows

### Additional context

launching from Feather Client

**Comment by TonimatasDEV** [comment]
It can be closed as duplicated [301](https://github.com/kettingpowered/Ketting-1-20-x/issues/301)
