### ISSUE TITLE
Crash server with connector or something  

### ISSUE THREAD

**Issue by ndinhhai201** [kettingpowered/kettinglauncher#40]
### Basic questions:

- [X] I am using the latest Ketting launcher version at the time of writing.
- [X] I am not running my server in a onedrive folder.
- [X] I have provided full logs and not a screenshot.
- [X] I am having an issue with ketting and not the ketting launcher.
- [X] I have checked all items without reading.
- [X] I have provided proper reproduction steps.

### Ketting launcher Version

newest version

### Description of behavior

Start server and get crash

### Reproduction Steps

```markdown
Steps to reproduce the behavior:
1. Use above Version with newsest version
2. Run the server
3. See the error
```

### Logs

[latest.log](https://github.com/user-attachments/files/16421545/latest.log)

### JVM Flags

--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15

**Comment by JustRed23** [comment]
This is not an issue with ketting, as mentioned here https://github.com/TerraformersMC/Biolith/issues/13
Also please make sure to correctly fill out the issue template
