### ISSUE TITLE
A critical error has occurred and server was shut down.

### ISSUE THREAD

**Issue by ndinhhai201** [kettingpowered/kettinglauncher#41]
### Basic questions:

- [X] I am using the latest Ketting launcher version at the time of writing.
- [X] I am not running my server in a onedrive folder.
- [X] I have provided full logs and not a screenshot.
- [X] I am having an issue with ketting and not the ketting launcher.
- [ ] I have checked all items without reading.
- [X] I have provided proper reproduction steps.

### Ketting launcher Version

newest version

### Description of behavior

Crash server when start

### Reproduction Steps

```markdown
Steps to reproduce the behavior:
1. Use above Version with
2. Run the server
3. See the error
```

### Logs

[A critical error has occurred and your server was shut down..log](https://github.com/user-attachments/files/16424728/A.critical.error.has.occurred.and.your.server.was.shut.down.log)

**Comment by ndinhhai201** [comment]
A critical error has occurred and your server was shut down. I'm testing Ketting with mods that are likely to cause errors

**Comment by JustRed23** [comment]
Make sure to make tickets in the right repository ;)
https://github.com/kettingpowered/Ketting-1-20-x

**Comment by JustRed23** [comment]
Also, Fabric mods will rarely work correctly with Forge as some functions are just entirely different, this is not an issue on our end
